//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApproval.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseApproval.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@type&quot;: &quot;MessageCard&quot;,
        ///  &quot;@context&quot;: &quot;http://schema.org/extensions&quot;,
        ///  &quot;summary&quot;: &quot;This is the summary property&quot;,
        ///  &quot;themeColor&quot;: &quot;0075FF&quot;,
        ///  &quot;sections&quot;:
        ///  [
        ///    {
        ///      &quot;heroImage&quot;:
        ///      {
        ///        &quot;image&quot;: &quot;http://messagecardplayground.azurewebsites.net/assets/FlowLogo.png&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;startGroup&quot;: true,
        ///      &quot;title&quot;: &quot;{{approvalResult}}&quot;,
        ///      &quot;activityImage&quot;: &quot;http://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg&quot;,
        ///      &quot;activityTitle&quot;: &quot;Requested by [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string refreshCard {
            get {
                return ResourceManager.GetString("refreshCard", resourceCulture);
            }
        }
    }
}
